language: go
sudo: required 
go:
  - "1.10"

env:
  global:
  - CODECOV_TOKEN="a22f58ec-7a51-470e-9b9d-2835fb38a154"

services:
  - postgresql
  
addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE USER db_book_store WITH PASSWORD 'bukapassword';" -U postgres
  - psql -c "CREATE USER db_book_store_test WITH PASSWORD 'bukapassword';" -U postgres